### PR TITLE
2 kirwa init project

### LINKED ISSUE #2: init project
setup docker compose with:
- frontend: vite react ts, tailwind
- backend: nest, prisma
- webserver: nginx
- database: postgres

### LINKED ISSUE #6: optimize docker compose up
install node_modules in build time not in run time for frontend and backend

### PR DESCRIPTION
**Pull request by kirwako**
I add step for creating .env file
and I remove test files

### CODE REVIEW

**Review by aithmid — APPROVED** [review]
works fine

**Comment by kirwako** [comment]
@twelve0  I edited the redme

**Review by aithmid — APPROVED** [review]
seems good

**Review by procrastinator-101 — APPROVED** [review]
all is well

**Review by benlyazid — APPROVED** [review]

**Pull request merged**
