### PR TITLE
feat: add project schema

### LINKED ISSUE #12: add database schema
add database schema to prisma

### PR DESCRIPTION
**Pull request by aithmid**
I added models in prisma schema

### CODE REVIEW

**Comment by kirwako** [comment]
please add a way how to test is this schema work

**Comment by aithmid** [comment]
@benlyazid is working on adding a seeder to test it

**Comment by kirwako** [comment]
I am talking about how migration not the data inside it

**Review by kirwako — CHANGES_REQUESTED** [review]
3. there is a typo in `model Chennel {`
please change `Chennel` to `Channel`
2. and `Member                 Member[]` to `members                 Member[]` in line 27
3. and `Message                 Message[]` to `messages                 Message[]` in line 28
4.  and `User                 User[]` to `users                 User[]` in line 48
5. in line 60 this `lastMessagdID Int` can be great by making it a foreign key of message
6. in line 76 there is chennel typo `Chennel   Chennel      @relation(fields: [chennelId], references: [id])`
7. same as above for line 77, 97 and 99

**Comment by aithmid** [comment]
@kirwa-KO fixed everything except (7 - in line 60 this lastMessagdID Int can be great by making it a foreign key of message)
it would add a naming conflict, and fixing it would add a lot of unnecessary fields

**Comment by aithmid** [comment]
> please add a way how to test is this schema work

you mean `npx prisma migrate dev --name "test" `?

**Comment by kirwako** [comment]
yes

**Review by kirwako — APPROVED** [review]

**Pull request merged**
